name: changelog

on:
  release:
    types: [released]

jobs:
  update:
    name: reuse-changelog
    uses: shishifubing/ci-actions-common/.github/workflows/reuse-changelog.yml@main
    secrets: inherit
