name: release

on:
  schedule:
    # daily at 23:00 UTC
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  release:
    uses: shishifubing/ci-actions-common/.github/workflows/release.yml@main
    secrets: inherit
